# Generated by Django 4.1.1 on 2022-10-07 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('ContactId', models.AutoField(primary_key=True, serialize=False)),
                ('ContactName', models.CharField(max_length=100)),
                ('ContactNumber', models.CharField(max_length=20)),
                ('ContactEmail', models.EmailField(max_length=254)),
            ],
        ),
    ]
