# Generated by Django 4.1.1 on 2022-10-07 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_contacts_contactcreated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='ContactCreated',
            field=models.DateField(auto_now_add=True),
        ),
    ]
